"""
reel.py — Acme brief-driven reel runner (M4 -> M5), 0 Higgsfield credits.

Turns a job folder into a finished, branded reel — no hand-editing of HTML. Two
models, auto-selected by the brief:

  • OVERLAY (default, Marvin 2026-06-20) — brief.overlay present. The caption lives
    in a TRANSPARENT brand template (reel-overlay-* family) composited over the CLEAN
    video (brief.video) by produce.py --video-underlay. The caption is NEVER burned
    into the video — it sits in the template, exactly as the template is designed.
    No caption_data.json / hyperframes needed. Writes <job>/<job_id>-final.mp4 + thumb.png.

  • LEGACY burned-in (brief.cover + caption_data.json) — word-synced karaoke captions
    rendered INTO the video via hyperframes-captions, then a branded cover poster. Kept
    for reels that still want burned, time-synced captions.

Usage:
    python3 reel.py output/jobs/ACME-007            # auto-detects overlay vs legacy
    python3 reel.py output/jobs/ACME-007 --skip-cover   # legacy only: captions, no M5 cover

Job folder contract:
    brief.json          # M1 contract (see schemas/brief.schema.json)
    caption_data.json   # { duration, uniform_cream, words[], blocks[] }  (authored from the transcript)
    -> writes: <job>/captioned.mp4, <job>/<job_id>-final.mp4, <job>/thumb.png, <job>/_build/

What it does:
    1. Reads brief.json + caption_data.json.
    2. Builds an isolated copy of hyperframes-captions/ in <job>/_build/.
    3. Copies the source video in as input.mp4; injects the caption-data block
       (between the ACME-CAPTION-DATA markers) and rewrites every data-duration.
    4. Lints + validates, then renders -> <job>/captioned.mp4.
    5. M5: produce.py renders the branded cover from brief.cover and embeds it
       as the mp4 poster + standalone thumb.png (run with --no-log).
"""

import argparse
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

WORKSPACE = Path(__file__).parent.resolve()
CAPTIONS_SRC = WORKSPACE / "hyperframes-captions"
PRODUCE = str(WORKSPACE / "produce.py")
HF = ["npx", "--yes", "hyperframes@0.6.64"]

# Files/dirs copied from the captions template into each job build.
TEMPLATE_ITEMS = ["index.html", "compositions", "fonts", "hyperframes.json", "package.json", "meta.json"]
COMPONENT_REL = "compositions/components/caption-editorial-emphasis.html"
DATA_MARKER = re.compile(r"// >>> ACME-CAPTION-DATA.*?// <<< ACME-CAPTION-DATA <<<", re.DOTALL)


def fail(msg: str) -> "NoReturn":
    sys.exit(f"[reel] ERROR: {msg}")


def build_data_block(cap: dict) -> str:
    """Render the JS caption-data block from caption_data.json (JSON is valid JS here)."""
    duration = cap["duration"]
    uniform = "true" if cap.get("uniform_cream", True) else "false"
    words = json.dumps(cap["words"], ensure_ascii=False)
    blocks = json.dumps(cap["blocks"], ensure_ascii=False)
    return (
        "// >>> ACME-CAPTION-DATA — generated by reel.py from caption_data.json. Do not hand-edit. >>>\n"
        f"      var DURATION = {duration};\n"
        f"      var UNIFORM_CREAM = {uniform};\n"
        f"      var W = {words};\n"
        f"      var BLOCKS = {blocks};\n"
        "      // <<< ACME-CAPTION-DATA <<<"
    )


def run(cmd, cwd=None) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)


def run_overlay_reel(job, brief, overlay):
    """NEW reel model (Marvin 2026-06-20): caption lives in the brand TEMPLATE OVERLAY,
    never burned into the video. The clean source video (brief.video — reel_video.py keeps
    it caption-free by design) is the underlay; produce.py --video-underlay renders the
    overlay template as a transparent RGBA layer and composites it over every frame.

    Contract — brief.overlay:
        { "template": "templates/src/reel-overlay-broll-dark.html",
          "EYEBROW": "...", "BRAND_NAME": "ACME LABS",
          "HOOK_LINE_1": "...", "HOOK_LINE_2_ITALIC": "...", "HOOK_LINE_3": "...",
          "SUBTITLE_TEXT": "...", "CTA_LABEL": "...", "HANDLE": "@acmelabs" }

    No caption_data.json / hyperframes needed — that's the legacy burned-in path.
    """
    template = overlay.get("template")
    if not template or not (WORKSPACE / template).exists():
        fail(f"brief.overlay.template missing or not found: {template!r}")
    if "video" not in brief:
        fail("overlay reel needs brief.video (the clean source video underlay)")
    video_src = (WORKSPACE / brief["video"]).resolve()
    if not video_src.exists():
        fail(f"source video not found: {video_src}")

    final = job / f"{brief['job_id']}-final.mp4"
    cmd = ["python3", PRODUCE, template, str(final), "--video-underlay", str(video_src), "--no-log"]
    # reel-overlay templates CONTAIN the video in a design window (top:20% left:18% right:18%
    # bottom:20% of 1080×1920 = 692×1152 at 194,384); the caption sits OUTSIDE that box. Place
    # the clean video into the window; the band colour follows the theme.
    if "reel-overlay" in template:
        is_light = template.endswith("-light.html")
        cmd += ["--window", "194,384,692,1152", "--band", "#F2EDE4" if is_light else "#1A2E1E"]
    # Synced spoken captions: overlay the script, timed to the narration (voiceover) length.
    script = brief.get("script", "").strip()
    narr = job / "narration.wav"
    if script:
        cmd += ["--captions-script", script]
        if narr.exists():
            pr = subprocess.run(["ffprobe", "-v", "error", "-show_entries", "format=duration",
                                 "-of", "default=nw=1:nk=1", str(narr)], capture_output=True, text=True)
            try:
                cmd += ["--captions-dur", f"{float(pr.stdout.strip()):.2f}"]
            except ValueError:
                pass
    for k, v in overlay.items():
        if k == "template":
            continue
        cmd += ["--set", f"{k}={v}"]
    r = run(cmd, cwd=WORKSPACE)
    if r.returncode != 0 or not final.exists():
        fail(f"produce.py --video-underlay failed:\n{(r.stdout + r.stderr)[-1500:]}")

    # Relocate the standalone poster produce.py drops in output/ → job/thumb.png.
    thumbs = sorted((WORKSPACE / "output").glob(f"{Path(template).stem}-*-thumb.png"))
    if thumbs:
        shutil.move(str(thumbs[-1]), str(job / "thumb.png"))
    print(f"[reel] overlay composited (clean video + template caption) -> {final}", file=sys.stderr)
    print(f"final={final}")
    print(f"thumb={job / 'thumb.png'}")


def main():
    ap = argparse.ArgumentParser(description="Acme brief-driven reel runner (M4->M5)")
    ap.add_argument("job_dir", help="Job folder containing brief.json + caption_data.json")
    ap.add_argument("--skip-cover", action="store_true", help="Skip M5 (captions only)")
    ap.add_argument("--skip-check", action="store_true", help="Skip lint/validate (faster re-renders)")
    args = ap.parse_args()

    job = Path(args.job_dir).resolve()
    brief_path = job / "brief.json"
    cap_path = job / "caption_data.json"
    if not brief_path.exists():
        fail(f"no brief.json in {job}")
    brief = json.loads(brief_path.read_text())
    if brief.get("type") != "reel":
        fail(f"brief type is {brief.get('type')!r}; reel.py only handles type=reel")

    # ── NEW video-underlay overlay model: caption in the template, clean video underlay ──
    overlay = brief.get("overlay")
    if overlay:
        run_overlay_reel(job, brief, overlay)
        return

    # ── LEGACY burned-in caption model (hyperframes karaoke captions) ──
    cap_name = brief.get("caption_data", "caption_data.json")
    cap_path = job / cap_name
    if not cap_path.exists():
        fail(f"no {cap_name} in {job} — transcribe + author the caption beats first")
    cap = json.loads(cap_path.read_text())
    for k in ("duration", "words", "blocks"):
        if k not in cap:
            fail(f"{cap_name} missing required key {k!r}")

    video_src = (WORKSPACE / brief["video"]).resolve()
    if not video_src.exists():
        fail(f"source video not found: {video_src}")

    # 1. Build an isolated copy of the captions project.
    build = job / "_build"
    if build.exists():
        shutil.rmtree(build)
    build.mkdir(parents=True)
    for item in TEMPLATE_ITEMS:
        src = CAPTIONS_SRC / item
        dst = build / item
        if src.is_dir():
            shutil.copytree(src, dst)
        else:
            shutil.copy2(src, dst)
    shutil.copy2(video_src, build / "input.mp4")
    print(f"[reel] built {build}  (video -> input.mp4)", file=sys.stderr)

    # 2. Inject caption data between the markers.
    comp = build / COMPONENT_REL
    comp_text = comp.read_text()
    if not DATA_MARKER.search(comp_text):
        fail("ACME-CAPTION-DATA markers not found in caption component")
    comp.write_text(DATA_MARKER.sub(lambda _: build_data_block(cap), comp_text))

    # 3. Sync every data-duration to the clip length (compiler reads these statically).
    dur = cap["duration"]
    for f in (build / "index.html", comp):
        t = f.read_text()
        f.write_text(re.sub(r'data-duration="[^"]*"', f'data-duration="{dur}"', t))
    print(f"[reel] caption data injected · duration={dur}s · uniform_cream={cap.get('uniform_cream', True)}", file=sys.stderr)

    # 4. Lint + validate (gate), then render.
    if not args.skip_check:
        for stage in ("lint", "validate"):
            r = run(HF + [stage], cwd=build)
            if r.returncode != 0:
                fail(f"hyperframes {stage} failed:\n{(r.stdout + r.stderr)[-1500:]}")
            print(f"[reel] {stage} OK", file=sys.stderr)

    captioned = job / "captioned.mp4"
    r = run(HF + ["render", "--output", str(captioned)], cwd=build)
    if r.returncode != 0 or not captioned.exists():
        fail(f"render failed:\n{(r.stdout + r.stderr)[-1500:]}")
    print(f"[reel] rendered -> {captioned}", file=sys.stderr)

    if args.skip_cover:
        print(f"captioned={captioned}")
        return

    # 5. M5 — branded cover + embed (produce.py, --no-log for the test pipeline).
    cover = brief.get("cover")
    if not cover or "template" not in cover:
        fail("brief has no cover.template — pass --skip-cover or add a cover block")
    final = job / f"{brief['job_id']}-final.mp4"
    cmd = ["python3", PRODUCE, cover["template"], str(final), "--video", str(captioned), "--no-log"]
    for k, v in cover.items():
        if k == "template":
            continue
        cmd += ["--set", f"{k}={v}"]
    r = run(cmd, cwd=WORKSPACE)
    if r.returncode != 0 or not final.exists():
        fail(f"produce.py (M5) failed:\n{(r.stdout + r.stderr)[-1500:]}")
    # Relocate the standalone thumbnail produce.py drops in output/.
    thumbs = sorted((WORKSPACE / "output").glob(f"{Path(cover['template']).stem}-*-thumb.png"))
    if thumbs:
        shutil.move(str(thumbs[-1]), str(job / "thumb.png"))
    print(f"[reel] M5 cover embedded -> {final}", file=sys.stderr)

    print(f"captioned={captioned}")
    print(f"final={final}")
    print(f"thumb={job / 'thumb.png'}")


if __name__ == "__main__":
    main()
